# Generated by Django 4.2.19 on 2025-02-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0005_alter_message_conversation'),
    ]

    operations = [
    ]
