# Generated by Django 4.2.19 on 2025-02-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0006_auto_20250226_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='messaging_app.conversation'),
        ),
    ]
