# Generated by Django 4.2.19 on 2025-03-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0010_rename_users_conversation_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='created_at',
        ),
    ]
